---
global:
  scrape_interval: "15s"
scrape_configs:
- job_name: "prometheus"
  scrape_interval: "5s"
  static_configs:
  - targets:
    - "localhost:1111"
    labels:
      __metrics_path__: "/actuator/prometheus"
